apiVersion: v1   
kind: Service
metadata:
  name: mc-service
  namespace: default
spec:
  selector:
    app: mc
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: mc
    protocol: TCP
    port: 25565
    targetPort: 25565
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mc-deployment
  namespace: default
  labels:
    app: mc
spec:
  minReadySeconds: 15
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - name: mc
        image: lacledeslan/gamesvr-minecraft:java
        imagePullPolicy: Always
        ports:
        - containerPort:  25565
          name: mc
        volumeMounts:
        - name: mc-volume
          mountPath: /home/app/config
          readOnly: true
        envFrom:
        - configMapRef:
            name: mc-configmap
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 256M
        #   limits:
        #     cpu: 120m
        #     memory: 512M
        # livenessProbe:
        #   tcpSocket:
        #     port: 25565
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /api/v1/health/liveness
        #     port: 8090
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 5
      restartPolicy: Always
      # imagePullSecrets:
      # - name : etz-ecr
      volumes:
      - name: mc-volume
        projected:
          sources:
          - configMap:
              name: mc-configmap


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-configmap
  namespace: default
data:
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "server: hide";
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /mc(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: mc-service
            port:
              name: mc
